module.exports = {
  SOCKET_CONNECT: 'connection',
  SOCKET_DISCONNECT: 'disconnect',
  USER_CONNECT: 'USER_CONNECT',
  USER_INFO: 'USER_INFO',
  USER_OPTIONS: 'USER_OPTIONS',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_DISCONNECTED: 'USER_DISCONNECTED'
}